### ISSUE TITLE
How do I use group in RPC

### ISSUE THREAD

**Issue by cmkcmk181** [zeromicro/go-zero#1851]
如何在rpc项目中有多个模块功能，在不进行拆分微服务的情况下如何进行划分目录？在goctl命令中没找到类似group的生成参数。

**Comment by kevwan** [comment]
RPC is controlled by protoc, no groups available.

**Comment by cmkcmk181** [comment]
用什么解决方案吗？否则logic目录下岂不是一大堆文件？

**Comment by kevwan** [comment]
Right now, no solution.

**Comment by fynxiu** [comment]
@kevwan 
Could we use specific annotations(comments) to implement the grouping feature?

**Comment by fynxiu** [comment]
`ProtocolBuffers` V3 does not support grouping, if developers define too many RPC functions (referred to as RPC), the logic directory will generate the same number of files, which affects the readability of the project; and currently `goctl` uses a third-party parsing tool as the basis for code generation. In view of the above two points, we propose the following design solution.

Add comments starting with `/// @ZeroGroup:` to the `Service` of the `proto` file to implement RPC grouping. We refer to a conforming comment as an RPC grouping comment.

An RPC can be either grouped or ungrouped. An ungrouped RPC will keep the same design idea as the original version, while a grouped RPC will be grouped according to the group name, so that each RPC will have the attributes of whether it is grouped or not and the group name, which will be used as the basis for code generation.

An RPC is considered an ungrouped RPC if there is no RPC grouping annotation above its position, otherwise it is considered a grouped RPC, and the group of an RPC is always the group referred to by the nearest RPC grouping annotation above its position.

As shown in the code below, `Baz` is considered an ungrouped RPC because it does not have any grouping annotations above its position. `Foo` has the nearest RPC grouping annotation above its position as `/// @ZeroGroup: foo`, so its grouping is `foo`. Similarly, the grouping of `Bar` is `bar`.

``` proto
  // Baz is a ungrouped rpc.
  rpc Baz(BazRequest) returns (BazResponse);

  /// @ZeroGroup: foo

  // Foo is a rpc of group `foo`.
  rpc Foo(FooRequest) returns (FooResponse);

  /// @ZeroGroup: bar
  // Bar is a rpc of group `bar`.
  // secondary comment line.
  rpc Bar(BarRequest) returns (BarResponse);
```

**Comment by crazy6995** [comment]
> `ProtocolBuffers` V3 does not support grouping, if developers define too many RPC functions (referred to as RPC), the logic directory will generate the same number of files, which affects the readability of the project; and currently `goctl` uses a third-party parsing tool as the basis for code generation. In view of the above two points, we propose the following design solution.
> 
> Add comments starting with `/// @ZeroGroup:` to the `Service` of the `proto` file to implement RPC grouping. We refer to a conforming comment as an RPC grouping comment.
> 
> An RPC can be either grouped or ungrouped. An ungrouped RPC will keep the same design idea as the original version, while a grouped RPC will be grouped according to the group name, so that each RPC will have the attributes of whether it is grouped or not and the group name, which will be used as the basis for code generation.
> 
> An RPC is considered an ungrouped RPC if there is no RPC grouping annotation above its position, otherwise it is considered a grouped RPC, and the group of an RPC is always the group referred to by the nearest RPC grouping annotation above its position.
> 
> As shown in the code below, `Baz` is considered an ungrouped RPC because it does not have any grouping annotations above its position. `Foo` has the nearest RPC grouping annotation above its position as `/// @ZeroGroup: foo`, so its grouping is `foo`. Similarly, the grouping of `Bar` is `bar`.
> 
> ```proto
>   // Baz is a ungrouped rpc.
>   rpc Baz(BazRequest) returns (BazResponse);
> 
>   /// @ZeroGroup: foo
> 
>   // Foo is a rpc of group `foo`.
>   rpc Foo(FooRequest) returns (FooResponse);
> 
>   /// @ZeroGroup: bar
>   // Bar is a rpc of group `bar`.
>   // secondary comment line.
>   rpc Bar(BarRequest) returns (BarResponse);
> ```

非常赞的思路，等一个实现。

**Comment by seosite** [comment]
> we propose the following design solution.

I am looking forward to it and hope it will come true as soon as possible

**Comment by waltcow** [comment]
New this feature

**Comment by seosite** [comment]
Need this feature

**Comment by waltcow** [comment]
RPC group 这一块用comment 去comments 去划分组（ /// @ZeroGroup）个人感觉会更通用吧
现在 -multiple是基于service 层面去做，生成的一堆的grpc client @anqiansong
