### ISSUE TITLE
How to bulk update if the model was generated with cache?

### ISSUE THREAD

**Issue by fuckqqcom** [zeromicro/go-zero#2211]
如题:
  goctl 生成带缓存的时候，怎么批量更新，是一条条for循环更新，还是先批量查出来id集合，是更新完在删除id集合？

**Comment by Mikaelemmmm** [comment]
This still depends on the scenario, if the performance requirements are not so extreme, in fact, for loop one update is not a big problem, if the amount is very large also have performance problems batch may be better, usually the first is easier, the second will be some trouble, because if you only have a primary key cache okay, if there are multiple secondary index cache to delete the corresponding secondary index cache, usually the first situation is enough to use
