### ISSUE TITLE
增加熔断开关/add  circuit breaker switch

### ISSUE THREAD

**Issue by Joewt** [zeromicro/go-zero#2322]
go-zero启动的时候，bindFeaturedRoutes那里有很多功能都是写死的，希望可以做成可配置可选的功能，比如熔断。
When Go-Zero launches, bindFeaturedRoutes has a number of features written dead, hoping to make it configurable and optional, such as circuit breaker.

**Comment by yinrenxin** [comment]
一个协程处理api，另外一个协程处理异步任务，异步任务的出错可能会影响到api(因为这2个协程用到了同一个conf)，这个时候我就想取消熔断，通过其他方式做处理
One coroutine handles the API, and the other handles asynchronous tasks. An error in the asynchronous task may affect the API (because the two coroutines use the same CONF). In this case, I want to cancel the circuit breaker and do something else

**Comment by jsonMark** [comment]
> go-zero启动的时候，bindFeaturedRoutes那里有很多功能都是写死的，希望可以做成可配置可选的功能，比如熔断。 When Go-Zero launches, bindFeaturedRoutes has a number of features written dead, hoping to make it configurable and optional, such as circuit breaker.

你们是有硬性需求吗？zero就是工具大于约定！要是非必要，那就忍忍吧！

**Comment by yinrenxin** [comment]
> > go-zero启动的时候，bindFeaturedRoutes那里有很多功能都是写死的，希望可以做成可配置可选的功能，比如熔断。 When Go-Zero launches, bindFeaturedRoutes has a number of features written dead, hoping to make it configurable and optional, such as circuit breaker.
> 
> 你们是有硬性需求吗？zero就是工具大于约定！要是非必要，那就忍忍吧！

是的，稳定性测试有硬性指标

**Comment by nicklaros** [comment]
english please :(
