### ISSUE TITLE
Problem on redis hmget

### ISSUE THREAD

**Issue by long12310225** [zeromicro/go-zero#2399]
根源是redis.go的834行到837行

v, err := conn.HMGet(ctx, key, fields...).Result()
		if err != nil {
			return err
		}

由于使用的是redis-v8，v8本身有bug，怎样都不为空，len(v)最少都会是1，建议改成这样判断
v, err := conn.HMGet(ctx, key, filed...).Result()
	if !reflect.ValueOf(res).IsValid() {
		return nil, fmt.Errorf("GetHash failed,result empty")
	}

**Comment by chenquan** [comment]
For every field that does not exist in the hash, a nil value is returned. Because non-existing keys are treated as empty hashes, running HMGET against a non-existing key will return a list of nil values.

quote:https://redis.io/commands/hmget/

`toString` will handle nil.
https://github.com/zeromicro/go-zero/blob/bb0e76be477fa423255470a116f360e48265b009/core/stores/redis/redis.go#L2437

---
I hope this answer will answer your question

**Comment by duyabobo** [comment]
查询hmget命令，如果没有某个filed而又在hmget中查了这个field，那么这个field的value就返回空字符串。这是一种取舍，

> !reflect.ValueOf(res).IsValid()

这种判断不可取。 hmget name filed1 field2，如果field1 不存在，或者field2不存在，这里IsValid返回都是true。
