### ISSUE TITLE
【建议】希望能增加隐式转换

### ISSUE THREAD

**Issue by yuexing0921** [zeromicro/go-zero#981]
在浏览器的环境中，关于form表单的内容，如果不做特殊处理，一般input接收的都是string类型，

但是如果这个字段在后端的定义是一个int类型时，前端需要显示的把这个字段从string类型转译成int类型。

比如
``` js
formData['a'] = +formData['a']
formData['b'] = +formData['b']
formData['c'] = +formData['c']

post(url, formData)
```

类似这样的代码在前端做form提交时是比较多的，如果go-zero可以提供隐式转换，就可以大大的节省前端这类脏代码

比如
``` js
// 现在已有
a = 123  // 不报错
a = '123' // 类型错误
a = '123s' // 类型错误
post(url, formData)

// 增加
a = 123  // 不报错
a = '123' // 不报错
a = '123s' // 类型错误
post(url, formData)
```

**Comment by sjfxy** [comment]
你在传递的时候 肯定必须按照 后端定义的类型进行传递呀  后端肯定得规范呀  前端按照这个规范来呀  如果隐藏转换有的无法转换 这个得程序员在后端进行加上拦截器进行处理 然后进行上下文传递 这种可以更加开放 只不过官方的默认是 post json path form 进行自动进行到对象到前端

**Comment by yuexing0921** [comment]
> 你在传递的时候 肯定必须按照 后端定义的类型进行传递呀 后端肯定得规范呀 前端按照这个规范来呀 如果隐藏转换有的无法转换 这个得程序员在后端进行加上拦截器进行处理 然后进行上下文传递 这种可以更加开放 只不过官方的默认是 post json path form 进行自动进行到对象到前端

请看清楚，这个是在框架层次已经做完了，业务层接受的信息还是定义好的类型，是没有感知的。

**Comment by sjfxy** [comment]
自己搞呀&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月1日(星期三) 上午9:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tal-tech/go-zero] 【建议】希望能增加隐式转换 (#981)





  
你在传递的时候 肯定必须按照 后端定义的类型进行传递呀 后端肯定得规范呀 前端按照这个规范来呀 如果隐藏转换有的无法转换 这个得程序员在后端进行加上拦截器进行处理 然后进行上下文传递 这种可以更加开放 只不过官方的默认是 post json path form 进行自动进行到对象到前端
  
请看清楚，这个是在框架层次已经做完了，业务层接受的信息还是定义好的类型，是没有感知的。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by damiao-wang** [comment]
![image](https://user-images.githubusercontent.com/21240498/131598756-cb606e04-5f41-4751-80a6-b3ee8aaeb8e9.png)
输入是string  是有现成方案的。可以直接用 google.golang.org/protobuf/encoding/protojson，当然 需要proto来定义字段了。

另外 由于int64前端可能溢出，所以之前我们框架也会把int64转换为string传递给前端。这种需求很常见的，zero可以考虑下。

**Comment by Gstring-w** [comment]
前端js不是强类型，容易出现这个问题

**Comment by kevwan** [comment]
标题已经明确了这个问题的属性，隐式。

当你传一个string时结果正确，那么你可能压根都会不知道服务端原来要的是int。

go里面要把[]string转成[]interface{}也得自己搞，加一个容易，减一个太难。

调用方应该清楚的知道参数类型，不知道就搞明白，类型不对，那就转对。

保持简单！

**Comment by sjfxy** [comment]
真的难顶 把这些可配置 可扩展 交给大家自由发挥 才可以发挥 go的优势 少即是多 接口是最大特色&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kevin Wan ***@***.***&gt;
发送时间: 2021年9月3日 07:39
收件人: tal-tech/go-zero ***@***.***&gt;
抄送: sjfxy ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[tal-tech/go-zero] 【建议】希望能增加隐式转换 (#981)





 
标题已经明确了这个问题的属性，隐式。
 
当你传一个string时结果正确，那么你可能压根都会不知道服务端原来要的是int。
 
go里面要把[]string转成[]interface{}也得自己搞，加一个容易，减一个太难。
 
调用方应该清楚的知道参数类型，不知道就搞明白，类型不对，那就转对。
 
保持简单！
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
